name: CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Só roda após o job 'test' do CI passar
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Create artifact
      run: |
        zip -r calculator.zip calculator.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculadora-artifact
        path: calculadora.zip
